import streamlit as st
import tensorflow as tf
import numpy as np
from PIL import Image

# -----------------------------------
# Page Settings
# -----------------------------------
st.set_page_config(
    page_title="AI Eye Gender Classifier",
    page_icon="👁️",
    layout="wide"
)

# -----------------------------------
# Load Model
# -----------------------------------
@st.cache_resource
def load_model():
    return tf.keras.models.load_model("model.keras")

model = load_model()

IMG_SIZE = 128


# -----------------------------------
# Styling
# -----------------------------------
st.markdown("""
<style>

.stApp {
    background: #F1F5F9;
}

/* Remove default header */
header {
    visibility: hidden;
}

/* Main Banner */

.banner {
    background: linear-gradient(135deg,#2563EB,#7C3AED);
    padding: 35px;
    border-radius: 25px;
    text-align:center;
    color:white;
    margin-bottom:30px;
    box-shadow:0px 10px 30px rgba(37,99,235,0.25);
}

.banner h1 {
    font-size:45px;
    margin-bottom:10px;
}

.banner p {
    font-size:20px;
}


/* Cards */

.card {

    background:white;
    padding:25px;
    border-radius:22px;
    box-shadow:0px 8px 25px rgba(0,0,0,0.08);
    height:100%;
}


/* Upload */

[data-testid="stFileUploader"] {

    background:white;
    border-radius:15px;
    padding:15px;
    border:2px dashed #2563EB;

}


/* Prediction badge */

.badge {

    font-size:32px;
    font-weight:bold;
    padding:15px;
    border-radius:15px;
    text-align:center;
    background:#EFF6FF;
    color:#1D4ED8;
    margin:20px 0;

}


/* Confidence */

.confidence {

    background:#F8FAFC;
    padding:15px;
    border-radius:15px;
    text-align:center;

}


.small-text{

    color:#64748B;
    font-size:16px;

}

</style>

""", unsafe_allow_html=True)



# -----------------------------------
# Header
# -----------------------------------

st.markdown("""
<div class="banner">

<h1>👁️ AI Eye Gender Classification</h1>

<p>Deep Learning based image prediction system</p>

</div>
""", unsafe_allow_html=True)



# -----------------------------------
# Upload Image
# -----------------------------------

uploaded_file = st.file_uploader(
    "Upload an eye image",
    type=["jpg","jpeg","png"]
)



if uploaded_file:

    image = Image.open(uploaded_file).convert("RGB")


    left,right = st.columns(2)


    with left:

        st.markdown(
        '<div class="card">',
        unsafe_allow_html=True
        )

        st.subheader("📷 Input Image")

        st.image(
            image,
            use_container_width=True
        )

        st.markdown(
        '</div>',
        unsafe_allow_html=True
        )



    # preprocessing

    img = image.resize(
        (IMG_SIZE,IMG_SIZE)
    )

    img = np.array(img)/255.0

    img = np.expand_dims(
        img,
        axis=0
    )


    with st.spinner("AI is analyzing..."):

        prediction = model.predict(
            img,
            verbose=0
        )


    confidence = float(prediction[0][0])



    # Change labels if your dataset mapping is opposite

    if confidence >= 0.5:

        result = "👨 Male"
        score = confidence

    else:

        result = "👩 Female"
        score = 1-confidence



    with right:


        st.markdown(
        '<div class="card">',
        unsafe_allow_html=True
        )


        st.subheader("🤖 AI Prediction")


        st.markdown(
        f"""
        <div class="badge">
        {result}
        </div>
        """,
        unsafe_allow_html=True
        )


        st.markdown(
        f"""
        <div class="confidence">

        <h3>Confidence</h3>

        <h1>{score*100:.2f}%</h1>

        </div>
        """,
        unsafe_allow_html=True
        )


        st.progress(
            score
        )


        st.markdown(
        '<p class="small-text">Prediction generated by CNN model</p>',
        unsafe_allow_html=True
        )


        st.markdown(
        '</div>',
        unsafe_allow_html=True
        )


    st.success("Prediction completed successfully 🎯")



else:

    st.info(
        "👆 Upload an eye image to start prediction"
    )
